/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ThreadsIndexImport } from './routes/threads/index'
import { Route as ThreadsThreadIdImport } from './routes/threads/$threadId'
import { Route as ServersServerIdImport } from './routes/servers.$serverId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsIndexRoute = ThreadsIndexImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsThreadIdRoute = ThreadsThreadIdImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRoute,
} as any)

const ServersServerIdRoute = ServersServerIdImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdImport
      parentRoute: typeof rootRoute
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads': typeof ThreadsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads': typeof ThreadsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/': typeof ThreadsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servers/$serverId' | '/threads/$threadId' | '/threads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servers/$serverId' | '/threads/$threadId' | '/threads'
  id:
    | '__root__'
    | '/'
    | '/servers/$serverId'
    | '/threads/$threadId'
    | '/threads/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/servers/$serverId",
        "/threads/$threadId",
        "/threads/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/servers/$serverId": {
      "filePath": "servers.$serverId.tsx"
    },
    "/threads/$threadId": {
      "filePath": "threads/$threadId.tsx"
    },
    "/threads/": {
      "filePath": "threads/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
