name: Job setup

description: 'Sets up the environment for a job during CI workflow'

runs:
  using: composite
  steps:
    - name: Typecheck
      shell: bash
      run: yarn typecheck --affected

    - name: Lint
      shell: bash
      run: yarn lint --affected

    - name: Test
      shell: bash
      run: yarn test --affected

    - name: Build
      shell: bash
      run: yarn build --affected
