name: Main

on:
  push:
    branches:
      - main
      - action-testing
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Do you want to deploy?'
        type: boolean
        required: true

permissions:
  contents: read
  actions: read

# Only run one deploy workflow at a time
concurrency: production

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

defaults:
  run:
    shell: bash

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  checks:
    uses: ./.github/workflows/checks.yml
    needs: [setup]
    secrets: inherit
    with:
      lint-affected: ${{ needs.setup.outputs.lint-affected }}
      typecheck-affected: ${{ needs.setup.outputs.typecheck-affected }}
      test-affected: ${{ needs.setup.outputs.test-affected }}
      build-affected: ${{ needs.setup.outputs.build-affected }}

  deploy:
    runs-on: ubuntu-latest
    needs: [setup, checks]
    if: ${{ needs.setup.outputs.deploy-affected > 0 || inputs.deploy == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: './.github/actions/setup'

      - name: Deploy
        run: yarn deploy --filter server
        env:
          OPENAI_LLM_API_URL: ${{ vars.OPENAI_LLM_API_URL }}
          OPENAI_LLM_API_KEY: ${{ secrets.OPENAI_LLM_API_KEY }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

      - name: Secrets
        run: |
          echo '{
            "OPENAI_LLM_API_URL": "${{ vars.OPENAI_LLM_API_URL }}",
            "OPENAI_LLM_API_KEY": "${{ secrets.OPENAI_LLM_API_KEY }}"
          }' > secrets.json
          yarn workspace server wrangler secret bulk < secrets.json
        env:
          OPENAI_LLM_API_URL: ${{ vars.OPENAI_LLM_API_URL }}
          OPENAI_LLM_API_KEY: ${{ secrets.OPENAI_LLM_API_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
