name: PR

on:
  pull_request:

permissions:
  contents: read
  actions: read

concurrency:
  group: ${{ github.ref_name }}
  # Here we specify that we'll cancel any "in progress" workflow of the same group. Thus if we push, ammend a commit and push
  # again the previous workflow will be cancelled. This saves us github action build minutes and avoid any conflicts
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

defaults:
  run:
    shell: bash

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  checks:
    uses: ./.github/workflows/checks.yml
    needs: [setup]
    secrets: inherit
    with:
      lint-affected: ${{ needs.setup.outputs.lint-affected }}
      typecheck-affected: ${{ needs.setup.outputs.typecheck-affected }}
      test-affected: ${{ needs.setup.outputs.test-affected }}
      build-affected: ${{ needs.setup.outputs.build-affected }}
