name: PR

on:
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: read

concurrency:
  group: ${{ github.ref_name }}
  # Here we specify that we'll cancel any "in progress" workflow of the same group. Thus if we push, ammend a commit and push
  # again the previous workflow will be cancelled. This saves us github action build minutes and avoid any conflicts
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}

defaults:
  run:
    shell: bash

jobs:
  ci-setup:
    uses: ./.github/workflows/ci-setup.yml
    secrets: inherit

  ci-checks:
    uses: ./.github/workflows/ci-checks.yml
    needs: [ci-setup]
    secrets: inherit
    with:
      typecheck-projects: ${{ needs.ci-setup.outputs.typecheck-projects }}
      lint-projects: ${{ needs.ci-setup.outputs.lint-projects }}
      test-projects: ${{ needs.ci-setup.outputs.test-projects }}
      build-projects: ${{ needs.ci-setup.outputs.build-projects }}
